ALTER TABLE "CustomerContact" ADD COLUMN IF NOT EXISTS "tags" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "CustomerContact" ADD COLUMN IF NOT EXISTS "birthday" TIMESTAMP(3);

ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "commissionPercent" DOUBLE PRECISION;
