-- GST profile + invoice tax breakup + POS lite stock fields

ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "gstin" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "legalName" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "stateCode" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "defaultGstPercent" DOUBLE PRECISION;

ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "cgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "sgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "igstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "staffId" TEXT;

ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "stockQty" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "hsnCode" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "gstPercent" DOUBLE PRECISION;

ALTER TABLE "ProductSale" ADD COLUMN IF NOT EXISTS "invoiceId" TEXT;
ALTER TABLE "ProductSale" ADD COLUMN IF NOT EXISTS "staffId" TEXT;

CREATE INDEX IF NOT EXISTS "ProductSale_invoiceId_idx" ON "ProductSale"("invoiceId");
